:select_collections        :en_gb       Select Collections For History Query
:add        :en_gb       Add
:remove        :en_gb       Remove
:search        :en_gb       Search
:remove_from_list :en_gb Remove selected collection from the list
:not_collection    :en_gb   The '#1' is not a collection
:collection_added  :en_gb Collection added ...
:records_found :en_gb The query criteria found '#1' records
:searching :en_gb Searching...
:operation_info :en_gb  for operation please insert 1 for Insert (default) , 2 for Update , 3 for Delete
:group_by_date? :en_gb Group Results By Date?
:group_by_users? :en_gb Group Results By User Names?
:trail_unset_or_not_closed :en_gb Error, Trail is unset or not closed,Please draw a closed trail
:multiple_geom_selected :en_gb Multiple geometry is selected
:no_geom_selected :en_gb Please select an Area geometry type
:geom_type_isnt_area :en_gb Geometry is not compatible, please select an Area geometry type
